In [72]:
import pandas as pd
import sql_functions as sf
schema = 'organic_africa' # UPDATE 'TABLE_SCHEMA' based on schema used in class 
engine = sf.get_engine()

In [73]:
farmers_df = sf.get_dataframe(f'SELECT * FROM {schema}.all_farmers')
farmers_df.shape

(20610, 22)

In [74]:
male_by_area = farmers_df.loc[farmers_df['sex']=='male', 'area'].value_counts()
female_by_area = farmers_df.loc[farmers_df['sex']=='female', 'area'].value_counts()

#### Df gender_by_area shows gender by area sorted by asc total

In [81]:
gender_by_area = male_by_area.to_frame()
gender_by_area.columns=['male']
gender_by_area['female'] = female_by_area
gender_by_area.index.names = ['area']
gender_by_area['total'] = female_by_area+male_by_area
gender_by_area['total'] = gender_by_area['total'].astype(int)
gender_by_area['majority'] = gender_by_area[['male','female']].idxmax(axis=1)
gender_by_area.sort_values(by='total', ascending=False, inplace=True)
gender_by_area

                      male  female  total majority
area
Mbire                 4913    2772   7685     male
Binga                  318    1877   2195   female
Rushinga               543    1207   1750   female
Chimanimani            208    1452   1660   female
Mudzi                  480    1110   1590   female
Buhera                 267     885   1152   female
Chipinge               193     784    977   female
Mt Darwin              447     521    968   female
Beitbridge             104     509    613   female
Makoni                 102     195    297   female
Hwange                  99     190    289   female
Kwekwe                  29     241    270   female
Uzumbamarambapfungwe    78     179    257   female
Mwenezi                 17     156    173   female
Triangle                84      79    163     male
Karoi                   84      79    163     male
Mutoko                  33      93    126   female
Chivi                    6      88     94   female
Mushumbi                15      14     29     male

### Df gender_by_area_percent shows male female distribution by area

Majority of the farmers are **female**! Only in the areas *Mushumbi, Karoi, Triangle* the gender distribution is **50/50**. And *Mbire* is the only area with male majority

In [83]:
def calc_distr(row):
     row["male"] = round(row["male"]/row["total"], 4)
     row["female"] = round(row["female"]/row["total"], 4)
     row["total"] = row["male"]+row["female"]
     return row

In [84]:
gender_by_area_percent = gender_by_area.apply(calc_distr, axis=1)
gender_by_area_percent['male'] = gender_by_area_percent['male'].transform(lambda x: '{:,.0%}'.format(x), axis=0)
gender_by_area_percent['female'] = gender_by_area_percent['female'].transform(lambda x: '{:,.0%}'.format(x))
gender_by_area_percent['total'] = gender_by_area_percent['total'].transform(lambda x: '{:,.0%}'.format(x))
gender_by_area_percent.sort_values(by='female', ascending=False, inplace=True)
gender_by_area_percent

                     male female total majority
area
Chivi                  6%    94%  100%   female
Mwenezi               10%    90%  100%   female
Kwekwe                11%    89%  100%   female
Chimanimani           13%    87%  100%   female
Binga                 14%    86%  100%   female
Beitbridge            17%    83%  100%   female
Chipinge              20%    80%  100%   female
Buhera                23%    77%  100%   female
Mutoko                26%    74%  100%   female
Mudzi                 30%    70%  100%   female
Uzumbamarambapfungwe  30%    70%  100%   female
Rushinga              31%    69%  100%   female
Makoni                34%    66%  100%   female
Hwange                34%    66%  100%   female
Mt Darwin             46%    54%  100%   female
Mushumbi              52%    48%  100%     male
Karoi                 52%    48%  100%     male
Triangle              52%    48%  100%     male
Mbire                 64%    36%  100%     male