lets import the 2018 tables

In [1]:
# Import get_dataframe function from the sql module
import pandas as pd 
from sql_functions import get_dataframe

In [2]:
schema = 'organic_africa'
df1 = get_dataframe(f'SELECT * FROM {schema}."OGInsp2018__OGMB_1"')

In [3]:
schema = 'organic_africa'
df3 = get_dataframe(f'SELECT * FROM {schema}."OG_Insp_2018__OGOrg_1"')

In [13]:
display(df3.shape, 
df1.shape)

(1004, 25)

(431, 26)

In [14]:
df3.columns

Index(['ID', 'Entered_by', 'Date_entered', 'OG_Nr', 'Date_inspected', 'Area',
       'LU_Internal_Inspector', 'Date_of_birth', 'HH_under_5_years_female',
       'HH_under_5_years_male', 'HH_5-17_years_female', 'HH_5-17_years_male',
       'HH_18-59_years_female', 'HH_18-59_years_male',
       'HH_over_60_years_female', 'HH_over_60_years_male', 'Months_food_lasts',
       'last_year_corrective_action', 'Corrective_action_implemented',
       'Compliance_this_year', 'Recurrent_corrective_actions',
       'Corrective_actions', 'Compliance_this_year_ICS',
       'Additional_sanctions_ICS', 'Overall_comment'],
      dtype='object')

In [15]:
df1.columns

Index(['ID', 'Entered_by', 'Date_entered', 'OG_Nr', 'Date_inspected', 'Area',
       'LU_Internal_Inspector', 'Date_of_birth', 'HH_under_5_years_female',
       'HH_under_5_years_male', 'HH_5-17_years_female', 'HH_5-17_years_male',
       'HH_18-59_years_female', 'HH_18-59_years_male',
       'HH_over_60_years_female', 'HH_over_60_years_male', 'Months_food_lasts',
       'last_year_corrective_action', 'Corrective_action_implemented',
       'Compliance_this_year', 'Recurrent_corrective_actions',
       'Corrective_actions', 'Compliance_this_year_ICS',
       'Additional_sanctions_ICS', 'Overall_comment', 'area_1'],
      dtype='object')

In [18]:
df1.drop(['area_1'], axis=1, inplace=True)

In [19]:
df1.columns

Index(['ID', 'Entered_by', 'Date_entered', 'OG_Nr', 'Date_inspected', 'Area',
       'LU_Internal_Inspector', 'Date_of_birth', 'HH_under_5_years_female',
       'HH_under_5_years_male', 'HH_5-17_years_female', 'HH_5-17_years_male',
       'HH_18-59_years_female', 'HH_18-59_years_male',
       'HH_over_60_years_female', 'HH_over_60_years_male', 'Months_food_lasts',
       'last_year_corrective_action', 'Corrective_action_implemented',
       'Compliance_this_year', 'Recurrent_corrective_actions',
       'Corrective_actions', 'Compliance_this_year_ICS',
       'Additional_sanctions_ICS', 'Overall_comment'],
      dtype='object')

In [22]:
# Convert column names to lowercase in df1
df1.rename(columns=str.lower, inplace=True)

# Convert column names to lowercase in df3
df3.rename(columns=str.lower, inplace=True)

In [23]:
df_2018 = pd.concat([df1, df3], ignore_index=True)

In [26]:
# how many nulls are there anyway
df1['og_nr'].isnull().sum()
df3['og_nr'].isnull().sum()

1

In [29]:
df_2018.head()

,id,entered_by,date_entered,og_nr,date_inspected,area,lu_internal_inspector,date_of_birth,hh_under_5_years_female,hh_under_5_years_male,...,hh_over_60_years_male,months_food_lasts,last_year_corrective_action,corrective_action_implemented,compliance_this_year,recurrent_corrective_actions,corrective_actions,compliance_this_year_ics,additional_sanctions_ics,overall_comment
0,355,79.0,2018-07-04,13647.0,2018-06-05,Karoi,Lunga,None,1.0,3,...,0,12.0,None,5.0,to be approved as non producer,None,None,None,None,None
1,147,79.0,2018-05-28,13475.0,2018-05-22,Triangle,Hoto M,1984-04-13,0.0,0,...,0,8.0,None,5.0,To approve with corrective actions,None,Improve hygiene,Approved without conditions,Improve hygiene,None
2,205,79.0,2018-05-29,13371.0,2018-05-21,Triangle,Hoto M,1956-07-06,4.0,0,...,1,9.0,None,5.0,To approve with corrective actions,None,Improve buffer zone,Approved without conditions,Improve buffer zone,None
3,337,79.0,2018-06-01,13659.0,2018-05-24,Karoi,Kundishora,None,2.0,2,...,0,12.0,None,5.0,To approve in full,None,To construct storage,Approved without conditions,Construct storage,None
4,343,79.0,2018-06-01,13686.0,2018-05-23,Karoi,Kundishora,None,0.0,1,...,1,6.0,None,5.0,To approve in full,None,To construct storage,Approved without conditions,To construct storage,None

In [30]:
df_2018.shape

(1435, 25)

In [41]:
df_2018.duplicated().sum()

431

In [46]:
duplicates = df_2018[df_2018['og_nr'].duplicated()]

In [48]:
df_2018['og_nr'].sort_values()

1399     1002.0
951      2770.0
970      2771.0
909      2772.0
1389     2773.0
         ...
1379    19828.0
1350    19829.0
1433    19830.0
320         NaN
763         NaN
Name: og_nr, Length: 1435, dtype: float64

In [54]:
df1.set_index('og_nr') #resetting index to be able to compare 
df3.set_index('og_nr')

,id,entered_by,date_entered,date_inspected,area,lu_internal_inspector,date_of_birth,hh_under_5_years_female,hh_under_5_years_male,hh_5-17_years_female,...,hh_over_60_years_male,months_food_lasts,last_year_corrective_action,corrective_action_implemented,compliance_this_year,recurrent_corrective_actions,corrective_actions,compliance_this_year_ics,additional_sanctions_ics,overall_comment
og_nr,,,,,,,,,,,,,,,,,,,,,
13124.0,6,79.0,2018-05-03,2018-03-18,Mbire,Ungani,1957-09-09,0.0,0,1,...,0,9.0,None,5.0,To approve with corrective actions,None,To build storage and drier,Approved without conditions,To construct group storage and dyre,None
13125.0,7,79.0,2018-05-03,2018-03-18,Mbire,Mapfudzeni,1971-12-06,1.0,0,3,...,0,4.0,None,5.0,To approve in full,None,To construct organic storage,Approved without conditions,Construct organic drier and storage,None
13126.0,8,79.0,2018-05-03,2018-03-18,Mbire,Matope,1969-02-02,1.0,1,1,...,0,10.0,None,5.0,To approve in full,None,Construct organic dryer and storage,Approved without conditions,To construct group storage and dyre,None
13127.0,9,79.0,2018-05-03,1974-03-18,Mbire,Matope,1974-10-04,1.0,1,1,...,0,12.0,None,5.0,To approve with corrective actions,None,Construct organic dryer and storage,Approved without conditions,To construct group storage and dyre,None
13128.0,10,79.0,2018-05-03,2018-03-18,Mbire,Mapfudzeni,1975-05-17,0.0,0,0,...,0,6.0,None,5.0,To approve in full,None,Construct storage,Approved without conditions,Construct organic storage and drier,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16230.0,1010,79.0,2018-11-12,2018-11-08,Makoni,Tendai,None,1.0,1,0,...,0,12.0,None,5.0,To approve in full,None,None,Approved without conditions,None,None
16236.0,1011,79.0,2018-11-12,2018-11-08,Makoni,Tendai,1969-06-10,1.0,1,1,...,0,12.0,None,5.0,To approve in full,None,None,Approved without conditions,None,None
16243.0,1012,79.0,2018-11-12,2018-11-08,Makoni,Tendai,None,0.0,1,1,...,0,12.0,None,5.0,To approve in full,None,None,Approved without conditions,None,None
19830.0,1013,79.0,2018-11-07,2020-09-22,Binga,Nyasha,1983-09-15,0.0,1,1,...,0,9.0,None,5.0,To approve with corrective actions,None,To implement ICS,Approved with conditions,To implement ICS,None
14116.0,1014,7.0,2018-11-14,1975-05-02,Binga,Norman,1975-05-02,0.0,0,0,...,0,4.0,None,5.0,To approve with corrective actions,None,None,Approved with conditions,None,None

In [56]:
#drop id column as it leads to confusion

df1.drop('id', axis=1, inplace=True)
df3.drop('id', axis=1, inplace=True)

In [61]:
df_2018 = pd.concat([df1, df3], ignore_index=True)

In [67]:
df_2018.drop_duplicates()

,entered_by,date_entered,og_nr,date_inspected,area,lu_internal_inspector,date_of_birth,hh_under_5_years_female,hh_under_5_years_male,hh_5-17_years_female,...,hh_over_60_years_male,months_food_lasts,last_year_corrective_action,corrective_action_implemented,compliance_this_year,recurrent_corrective_actions,corrective_actions,compliance_this_year_ics,additional_sanctions_ics,overall_comment
0,79.0,2018-07-04,13647.0,2018-06-05,Karoi,Lunga,None,1.0,3,0,...,0,12.0,None,5.0,to be approved as non producer,None,None,None,None,None
1,79.0,2018-05-28,13475.0,2018-05-22,Triangle,Hoto M,1984-04-13,0.0,0,1,...,0,8.0,None,5.0,To approve with corrective actions,None,Improve hygiene,Approved without conditions,Improve hygiene,None
2,79.0,2018-05-29,13371.0,2018-05-21,Triangle,Hoto M,1956-07-06,4.0,0,4,...,1,9.0,None,5.0,To approve with corrective actions,None,Improve buffer zone,Approved without conditions,Improve buffer zone,None
3,79.0,2018-06-01,13659.0,2018-05-24,Karoi,Kundishora,None,2.0,2,0,...,0,12.0,None,5.0,To approve in full,None,To construct storage,Approved without conditions,Construct storage,None
4,79.0,2018-06-01,13686.0,2018-05-23,Karoi,Kundishora,None,0.0,1,0,...,1,6.0,None,5.0,To approve in full,None,To construct storage,Approved without conditions,To construct storage,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,79.0,2018-11-12,16230.0,2018-11-08,Makoni,Tendai,None,1.0,1,0,...,0,12.0,None,5.0,To approve in full,None,None,Approved without conditions,None,None
1431,79.0,2018-11-12,16236.0,2018-11-08,Makoni,Tendai,1969-06-10,1.0,1,1,...,0,12.0,None,5.0,To approve in full,None,None,Approved without conditions,None,None
1432,79.0,2018-11-12,16243.0,2018-11-08,Makoni,Tendai,None,0.0,1,1,...,0,12.0,None,5.0,To approve in full,None,None,Approved without conditions,None,None
1433,79.0,2018-11-07,19830.0,2020-09-22,Binga,Nyasha,1983-09-15,0.0,1,1,...,0,9.0,None,5.0,To approve with corrective actions,None,To implement ICS,Approved with conditions,To implement ICS,None
1434,7.0,2018-11-14,14116.0,1975-05-02,Binga,Norman,1975-05-02,0.0,0,0,...,0,4.0,None,5.0,To approve with corrective actions,None,None,Approved with conditions,None,None

In [70]:
# Drop multiple columns 2
columns_to_drop = ['entered_by', 'lu_internal_inspector','last_year_corrective_action','corrective_action_implemented','compliance_this_year','recurrent_corrective_actions','corrective_actions','additional_sanctions_ics','compliance_this_year_ics','overall_comment']
df_2018.drop(columns=columns_to_drop, axis=1, inplace=True)





from IPython.display import display
# Display the merged DataFrame as a table
display(df_2018)

,date_entered,og_nr,date_inspected,area,date_of_birth,hh_under_5_years_female,hh_under_5_years_male,hh_5-17_years_female,hh_5-17_years_male,hh_18-59_years_female,hh_18-59_years_male,hh_over_60_years_female,hh_over_60_years_male,months_food_lasts
0,2018-07-04,13647.0,2018-06-05,Karoi,None,1.0,3,0,1,1,2,0,0,12.0
1,2018-05-28,13475.0,2018-05-22,Triangle,1984-04-13,0.0,0,1,1,0,0,1,0,8.0
2,2018-05-29,13371.0,2018-05-21,Triangle,1956-07-06,4.0,0,4,0,5,2,0,1,9.0
3,2018-06-01,13659.0,2018-05-24,Karoi,None,2.0,2,0,0,2,2,0,0,12.0
4,2018-06-01,13686.0,2018-05-23,Karoi,None,0.0,1,0,2,0,2,1,1,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,2018-11-12,16230.0,2018-11-08,Makoni,None,1.0,1,0,0,1,1,0,0,12.0
1431,2018-11-12,16236.0,2018-11-08,Makoni,1969-06-10,1.0,1,1,1,2,4,0,0,12.0
1432,2018-11-12,16243.0,2018-11-08,Makoni,None,0.0,1,1,1,1,3,0,0,12.0
1433,2018-11-07,19830.0,2020-09-22,Binga,1983-09-15,0.0,1,1,0,1,1,0,0,9.0
1434,2018-11-14,14116.0,1975-05-02,Binga,1975-05-02,0.0,0,0,1,1,1,0,0,4.0

In [72]:
import psycopg2
import sqlalchemy 
from sql_functions import sqlalchemy 
from sql_functions import get_engine 


# Write records stored in a dataframe to SQL database
engine = get_engine()
table_name = 'all_insp_2018'
if engine!=None:
    try:
        df_2018.to_sql(name='all_insp_2018', # Name of SQL table variable - at the front its the dataframe!! 
                        con=engine, # Engine or connection
                        schema='organic_africa', # your class schema variable
                        if_exists='replace', # Drop the table before inserting new values 
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None
else:
    print('No engine')

The all_insp_2018 table was imported successfully.